var path = require('path');

// Postgres DATABASE_URL = postgres://user:passwd@host:port/database
// SQLite	DATABASE_URL = sqlite://:@:/
var url = appGlobals.config.dataBaseURL.match(/(.*)\:\/\/(.*?)\:(.*)@(.*)\:(.*)\/(.*)/);
var DB_name  = (url[6]||null);
var user	 = (url[2]||null);
var pwd	 	 = (url[3]||null);
var protocol = (url[1]||null);
var dialect	 = (url[1]||null);
var port	 = (url[5]||null);
var host	 = (url[4]||null);
var storage = appGlobals.config.dataBaseStorage;

// Load ORM Model
var Sequelize = require('sequelize');

// Use SQLite or Postgres DB
var sequelize = new Sequelize(DB_name, user, pwd,
	{dialect:  protocol, 
	 protocol: protocol,
	 port:	   port,
	 host:     host,
	 storage:  storage, // only SQLite (.env)
	 omitNull: true,		// only Postgres
	 define: {
		 instanceMethods:{
			 /** 
			  * Check if object matches with instance. Useful for update checks 
			  * @method objectEquals 
			  * @param {Object} object Current object to be evaluated 
			  * @param {boolean} checkAutogen=false Check autogenerated values, such as createdAt or updatedAt
			  * @return {boolean}
			 */
			 //for (var obj in dcArray[0].dataValues){ if(obj !== 'createdAt' && obj !== 'updatedAt') console.log(obj);}
			 objectEquals: function(object, checkAutogen){
				if (object === undefined || object === null)
					return false;
				if (checkAutogen === undefined || checkAutogen === null)
					checkAutogen = false;
				for (var key in this.dataValues){
					if (!checkAutogen && (key === 'createdAt' || key === 'updatedAt'))
						continue;
					if (object[key] !== this[key])
						return false;
				}
				return true;
			}
		 }
	 }
   }
);

// Import definitions
//Type
var typePath = path.join(__dirname, 'type');
var Type = sequelize.import(typePath);
//Category
var categoryPath = path.join(__dirname, 'category');
var Category = sequelize.import(categoryPath);
//Component
var componentPath = path.join(__dirname, 'component');
var Component = sequelize.import(componentPath);
//Allergenic
var allergenicPath = path.join(__dirname, 'allergenic');
var Allergenic = sequelize.import(allergenicPath);
//Dish
var dishPath = path.join(__dirname, 'dish');
var Dish = sequelize.import(dishPath);
//Price
var pricePath = path.join(__dirname, 'price');
var Price = sequelize.import(pricePath);
//Image
var imagePath = path.join(__dirname, 'image');
var Image = sequelize.import(imagePath);
//DishComponent
var dishComponentPath = path.join(__dirname, 'dish_component');
var DishComponent = sequelize.import(dishComponentPath);
//DishAllergenic
var dishAllergenicPath = path.join(__dirname, 'dish_allergenic');
var DishAllergenic = sequelize.import(dishAllergenicPath);
// Stablish relationships
//Type-Dish (1-N)
Dish.belongsTo(Type, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
Type.hasMany(Dish);
//Category-Dish (N-M) - no need to define table in a separate file, as it doesn't have other atributes rather than FKs
var DishCategory = sequelize.define('DishCategory', {});
Category.belongsToMany(Dish, {through: 'DishCategory'});
Dish.belongsToMany(Category, {through: 'DishCategory'});
//Dish-Price (1-N)
Dish.hasMany(Price);
Price.belongsTo(Dish, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
//Dish-Image (1-N)
Dish.hasMany(Image);
Image.belongsTo(Dish, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});
//Dish-DishComponent (1-N)
Dish.hasMany(DishComponent);
DishComponent.belongsTo(Dish, {foreignKey: {allowNull: false}, onDelete: 'CASCATE'});
//DishComponent.belongsTo(Dish, {foreignKey: {allowNull: false}, onDelete: 'CASCATE'});
//Dish-DishAllergenic (1-N)
Dish.hasMany(DishAllergenic);
DishAllergenic.belongsTo(Dish, {foreignKey: {allowNull: false}, onDelete: 'CASCADE'});

// Exports
exports.Type = Type;
exports.Category = Category;
exports.Component = Component;
exports.Allergenic = Allergenic;
exports.Dish = Dish;
exports.Price = Price;
exports.Image = Image;
exports.DishCategory = DishCategory;
exports.DishComponent = DishComponent;
exports.DishAllergenic = DishAllergenic;
//Sequelize exports
//exports.sequelizeTransaction = Sequelize.prototype.transaction;//doesn't work without dependencies?
exports.resolvePromise = sequelize.Promise.resolve;

// Initialize database
//returning next element's count promise and using it in the next function is a way to keep the chain without nesting
//sample files have less than 10 rows for each model; for new tables with huge numbers of rows to be initialized, consider to use bulk operations
var fs = require('fs');
var samplesDir = appGlobals.config.modelSamplesDir;

sequelize.sync().then(function() {
	Type.count().then(
		//initial type inserts
		function(count){
			if (count === 0){
				var types = JSON.parse(fs.readFileSync(samplesDir + 'types.json', 'UTF-8'));
				for (var type in types){
					Type.create({
						id: type,
						text: types[type]
					});
				}
			}
			return Category.count();
		}
	).then(
		//initial category inserts
		function(count){
			if (count === 0){
				var categories = JSON.parse(fs.readFileSync(samplesDir + 'categories.json', 'UTF-8'));
				for (var category in categories){
					Category.create({
						id: category,
						text: categories[category]
					});
				}
			}
			return Component.count();
		}
	).then(
		//initial component inserts
		function(count){
			if (count === 0){
				var components = JSON.parse(fs.readFileSync(samplesDir + 'componentHints.json', 'UTF-8'));
				for (var component in components){
					Component.create({
						text: components[component]
					});
				}
			}
			return Allergenic.count();
		}
	).then(
		//initial allergenic inserts
		function(count){
			if (count === 0){
				var allergenics = JSON.parse(fs.readFileSync(samplesDir + 'allergenicHints.json', 'UTF-8'));
				for (var allergenic in allergenics){
					Allergenic.create({
						text: allergenics[allergenic]
					});
				}
			}
			return Dish.count();
		}
	).then(
		//initial dish inserts - types required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					Dish.create({
						id: dish.id,
						name: dish.name,
						description: dish.description,
						TypeId: dish.type //FK
					});
				}
			}
			return DishCategory.count();
		}
	).then(
		//initial dishCategory inserts - dish and category required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					if (dish.categories === undefined) { continue };
					for (var j = 0; j < dish.categories.length; j++){
						DishCategory.create({
							DishId: dish.id,
							CategoryId: dish.categories[j]
						});
					}
				}
			}
			return Price.count();
		}
	).then(
		//initial price inserts - dish required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					if (dish.Prices === undefined) { continue };
					for (var j = 0; j < dish.Prices.length; j++){
						Price.create({
							concept: dish.Prices[j].concept,
							price: dish.Prices[j].price,
							currency: dish.Prices[j].currency,
							DishId: dish.id
						});
					}
				}
			}
			return Image.count();
		}
	).then(
		//initial image inserts - dish required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					if (dish.Images === undefined) { continue };
					for (var j = 0; j < dish.Images.length; j++){
						Image.create({
							source: dish.Images[j].source,
							link: dish.Images[j].link,
							description: dish.Images[j].description,
							DishId: dish.id
						});
					}
				}
			}
			return DishComponent.count();
		}
	).then(
		//initial dishComponent inserts - dish required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					if (dish.Components === undefined) { continue };
					for (var index in dish.Components){
						DishComponent.create({
							text: dish.Components[index],
							DishId: dish.id
						});
					}
				}
			}
			return DishAllergenic.count();
		}
	).then(
		//initial dishAllergenic inserts - dish required
		function(count){
			if (count === 0){
				var dishDataDir = samplesDir + 'dishes/';
				var files = fs.readdirSync(dishDataDir);
				for (var i = 0; i < files.length; i++){
					var data = fs.readFileSync(dishDataDir + files[i], 'UTF-8');
					dish = JSON.parse(data);
					if (dish.Allergenics === undefined) { continue };
					for (var index in dish.Allergenics){
						DishAllergenic.create({
							text: dish.Allergenics[index],
							DishId: dish.id
						});
					}
				}
			}
			return DishAllergenic.count();			
		}
	//DEBUG - check data 
/*
	).then(	
		function(count){
			function printTable(tableRows){
				if (tableRows.length === 0)
					return;
				console.log('[Model: ' + tableRows[0].Model.tableName + ']');
				for (var i = 0; i < tableRows.length; i++){
					var strRow = JSON.stringify(tableRows[i]);
					var row = JSON.parse(strRow);
					delete row.createdAt;
					delete row.updatedAt;
					console.log(JSON.stringify(row));					
				}
			};
			//var models = [Type, Category, Component, Allergenic, Dish, Price, Image, DishCategory, DishComponent, DishAllergenic];
			models = [Price, DishComponent, DishAllergenic];
			for (var index in models){
				models[index].findAll().then(printTable);
			} 
		}
*/
	).then(function(count){ 
		return sequelize.Promise.resolve(count); }
	).then(function(count){
		console.log('Database initialization done');
	});
});
